### ISSUE TITLE
Years not change when changing the month

### ISSUE THREAD

**Issue by vincentwah** [appiphony/appiphony-lightning-js#38]
I'd like to bring this up to the team see whether it is a bug or not.

http://aljs.appiphony.com/#!/datepickers

Steps to reproduce the issue.
1. Go to http://aljs.appiphony.com/#!/datepickers
2. Click calendar icon and pop up the data picker.
3. By default, it shows current date, May 16, 2016 highlighted.
4. Click the left side arrow next to the month five times to switch the month to December.
5. The Year drop down remain 2016. Is it supposed to be changed to 2015?

**Comment by kevinberonilla** [comment]
Thanks for logging this! This is actually a bug that we need to address since Lightning UI's actual datepicker changes the year automatically. We will include this as part of the next release. Stay tuned!

**Comment by kevinberonilla** [comment]
Hi @vincentwah, can you please try this file? https://github.com/appiphony/appiphony-lightning-js/blob/development/dist/jquery/jquery.aljs-datepicker.min.js

That is the datepicker plugin from our `development` branch. I would advise using this single plugin (don't forget the `moment.js` dependency) instead of the `jquery.aljs-all.min.js` from the branch because there are several other plugins being reworked at the moment.
