### ISSUE TITLE
Picklist stops working after adding/removing items from dropdown

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#40]
As title says, I'm dynamically adding and removing items from picklist dropdown menu. 
Dropdown still shows, but onChange isn't called anymore. 
It still doesn't work even after another init call:
`$('[data-aljs="picklist"]').picklist({
        onChange: function(obj) {/*rest of the code here that isn't called after picklist update*/}
    });`

I would use <select> but style does not match SLDS so I would prefer to continue use picklist.

Browser Safari (latest) & Chrome (latest), aljs 1.0, SLDS 1.0.4

P.S.: using picklist('setValue', idToSelect, false); in JS console changes picklist value, but doesn't fire onChange.

**Comment by kevinberonilla** [comment]
Thanks for logging this, we will look into it when we can!

**Comment by kevinberonilla** [comment]
Hello @matejp84! It turns out you can use an existing method that we had previously chosen to leave out of documentation since we believed the plugin itself would only use it.

You can run the following method immediately after dynamically adding/removing picklist choices: `$('*picklist selector*').picklist('bindChoices')`

We will be adding documentation for this method in the next release, but you are able to use it now.

**Comment by jojoforce** [comment]
How do you add or remove pick list options dynamically?
