### ISSUE TITLE
multi-select on lookup disabled?

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#53]
Hi,

after upgrading to aljs 2.x I have noticed, that multi select on lookup component is not working anymore. Is this by design or am I doing something wrong?

Regards

**Comment by matejp84** [comment]
Any news on this issue?
Whenever I use data-select="single" on lookup it disappears when selecting an item. Also there is no html being built for pills under input as was in versions before.

**Comment by kevinberonilla** [comment]
Hi @matejp84! Yes, multi-select versions of Lookups are no longer supported by ALJS 2.0.0+ due to the fact that SLDS themselves have removed it from their component library. A custom solution would have to be developed to support something like this.

One example is wiring up the `onChange` callback to create SLDS pills on a separate container. See my example below:

```javascript
lookup.lookup({
    onChange: function(currentSelection, isAdd) {
        if (isAdd) {
            // Add an SLDS pill and its logic here. You can also use the ALJS Pill plugin to bind remove pill buttons
        }
    }
});
```

**Comment by matejp84** [comment]
Thanks for info :)
